check_PROGRAMS = sparse_test bim3_test
sparse_test_SOURCES = $(top_srcdir)/src/sparse.h $(top_srcdir)/src/sparse.cpp $(top_srcdir)/src/mumps_class.h $(top_srcdir)/src/mumps_class.cpp sparse_test.cpp $(top_srcdir)/src/mesh.h $(top_srcdir)/src/mesh.cpp $(top_srcdir)/src/operators.h $(top_srcdir)/src/operators.cpp 
bim3_test_SOURCES = $(top_srcdir)/src/sparse.h $(top_srcdir)/src/sparse.cpp $(top_srcdir)/src/mumps_class.h $(top_srcdir)/src/mumps_class.cpp bim3_test.cpp $(top_srcdir)/src/mesh.h $(top_srcdir)/src/mesh.cpp $(top_srcdir)/src/operators.h $(top_srcdir)/src/operators.cpp 
