ACLOCAL_AMFLAGS = -I m4
SUBDIRS = src data test examples/bgs \
          examples/tmesh_2d examples/adaptive_adr_2d \
          examples/bim3 examples/tmesh_3d \
	  examples/distributed_matrix examples/adaptive_adr_3d \
	  examples/shallow_water

dist_doc_DATA = README COPYING
include_HEADERS = src/bim_config.h src/bim_config_pre.h
