BIMMUMPSLIB = ../../src/libbimmumps.la @MUMPS_LIBS@ @MUMPS_EXTRA_LIBS@
BIMLISLIB   = ../../src/libbimlis.la @LIS_LIB@ @MUMPS_EXTRA_LIBS@
BIMP4ESTLIB = ../../src/libbimp4est.la @P4EST_LIB@
BIMLINALGLIB = ../../src/libbimlinalg.la 
BIMIOLIB    = @OCTAVE_FILE_IO_LDFLAGS@  @OCTAVE_FILE_IO_LIB@ @OCTAVE_LINK_FLAGS@ @OCTAVE_LINK_ADD@

BIMLIB           = ../../src/libbim.la
AM_CPPFLAGS      =  -I$(top_srcdir)/src -I$(top_srcdir)/test -I$(top_builddir)/src @MUMPS_CPPFLAGS@ @LIS_CPPFLAGS@ @OCTAVE_FILE_IO_CPPFLAGS@ @OCTAVE_COMPILE_FLAGS@ @OCTAVE_LINK_FLAGS@ 
BIMCHLIB         = ../../src/libbimsystemsolver.la
AM_LDFLAGS       = @MUMPS_LDFLAGS@ @LIS_LDFLAGS@
AUTOMAKE_OPTIONS = nostdinc

bin_PROGRAMS = main main_TG2IMEXRKC main_TG2IMEXRKC2PHASE main_lava #main_TG2IMEXRKCCUDA
CLEANFILES =

#swe_tg_SOURCES =  swe_tg.cpp
#swe_tg_CPPFLAGS =  $(AM_CPPFLAGS) @P4EST_CPPFLAGS@
#swe_tg_LDFLAGS =  $(AM_LDFLAGS)  @P4EST_LDFLAGS@
#swe_tg_LDADD = $(BIMLIB) $(BIMP4ESTLIB) $(BIMMUMPSLIB) $(BIMLINALGLIB) $(BIMIOLIB) @P4EST_LIB@
#CLEANFILES +=

#orography_SOURCES =  orography.cpp
#orography_CPPFLAGS =  $(AM_CPPFLAGS) @P4EST_CPPFLAGS@
#orography_LDFLAGS =  $(AM_LDFLAGS)  @P4EST_LDFLAGS@
#orography_LDADD = $(BIMLIB) $(BIMP4ESTLIB) $(BIMMUMPSLIB) $(BIMLINALGLIB) $(BIMIOLIB) @P4EST_LIB@
#CLEANFILES +=

#rusanov_SOURCES =  rusanov.cpp
#rusanov_CPPFLAGS =  $(AM_CPPFLAGS) @P4EST_CPPFLAGS@
#rusanov_LDFLAGS =  $(AM_LDFLAGS)  @P4EST_LDFLAGS@
#rusanov_LDADD = $(BIMLIB) $(BIMP4ESTLIB) $(BIMMUMPSLIB) $(BIMLINALGLIB) $(BIMIOLIB) @P4EST_LIB@
#CLEANFILES +=

main_SOURCES =  main.cpp Taylor_Galerkin.cpp
main_CPPFLAGS =  $(AM_CPPFLAGS) @P4EST_CPPFLAGS@
main_LDFLAGS =  $(AM_LDFLAGS)  @P4EST_LDFLAGS@
main_LDADD = $(BIMLIB) $(BIMP4ESTLIB) $(BIMMUMPSLIB) $(BIMLINALGLIB) $(BIMIOLIB) @P4EST_LIB@
CLEANFILES +=

main_TG2IMEXRKC_SOURCES =  main_TG2IMEX-RKC_Strang_balanced.cpp Taylor_Galerkin_IMEX-RKC_Strang_balanced.cpp #main_TG2IMEX-RKC.cpp Taylor_Galerkin_IMEX-RKC.cpp #main_TG2IMEX-RKC_Strang.cpp Taylor_Galerkin_IMEX-RKC_Strang.cpp
main_TG2IMEXRKC_CPPFLAGS =  $(AM_CPPFLAGS) @P4EST_CPPFLAGS@
main_TG2IMEXRKC_LDFLAGS =  $(AM_LDFLAGS)  @P4EST_LDFLAGS@
main_TG2IMEXRKC_LDADD = $(BIMLIB) $(BIMP4ESTLIB) $(BIMMUMPSLIB) $(BIMLINALGLIB) $(BIMIOLIB) @P4EST_LIB@
CLEANFILES += 

main_TG2IMEXRKC2PHASE_SOURCES =  main_TG2IMEX-RKC_Strang_balanced_two_phase.cpp Taylor_Galerkin_IMEX-RKC_Strang_balanced_two_phase.cpp #main_TG2IMEX-RKC.cpp Taylor_Galerkin_IMEX-RKC.cpp #main_TG2IMEX-RKC_Strang.cpp Taylor_Galerkin_IMEX-RKC_Strang.cpp
main_TG2IMEXRKC2PHASE_CPPFLAGS =  $(AM_CPPFLAGS) @P4EST_CPPFLAGS@
main_TG2IMEXRKC2PHASE_LDFLAGS =  $(AM_LDFLAGS)  @P4EST_LDFLAGS@
main_TG2IMEXRKC2PHASE_LDADD = $(BIMLIB) $(BIMP4ESTLIB) $(BIMMUMPSLIB) $(BIMLINALGLIB) $(BIMIOLIB) @P4EST_LIB@
CLEANFILES +=

main_lava_SOURCES =  main_lava.cpp Taylor_Galerkin_lava.cpp #main_TG2IMEX-RKC.cpp Taylor_Galerkin_IMEX-RKC.cpp #main_TG2IMEX-RKC_Strang.cpp Taylor_Galerkin_IMEX-RKC_Strang.cpp
main_lava_CPPFLAGS =  $(AM_CPPFLAGS) @P4EST_CPPFLAGS@
main_lava_LDFLAGS =  $(AM_LDFLAGS)  @P4EST_LDFLAGS@
main_lava_LDADD = $(BIMLIB) $(BIMP4ESTLIB) $(BIMMUMPSLIB) $(BIMLINALGLIB) $(BIMIOLIB) @P4EST_LIB@
CLEANFILES +=


#main_TG2IMEXRKCCUDA_SOURCES =  main_TG2IMEX-RKC_Strang_balanced_cuda.cpp Taylor_Galerkin_IMEX-RKC_Strang_balanced_cuda.cpp #main_TG2IMEX-RKC.cpp Taylor_Galerkin_IMEX-RKC.cpp #main_TG2IMEX-RKC_Strang.cpp Taylor_Galerkin_IMEX-RKC_Strang.cpp
#main_TG2IMEXRKCCUDA_CPPFLAGS =  $(AM_CPPFLAGS) @P4EST_CPPFLAGS@
#main_TG2IMEXRKCCUDA_LDFLAGS =  $(AM_LDFLAGS)  @P4EST_LDFLAGS@
#main_TG2IMEXRKCCUDA_LDADD = $(BIMLIB) $(BIMP4ESTLIB) $(BIMMUMPSLIB) $(BIMLINALGLIB) $(BIMIOLIB) @P4EST_LIB@
#CLEANFILES +=



